window:
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
  padding:
    x: 0
    y: 0

  
font:
  antialias: lcd
  hinting: true
  size: 12.0
  normal:
    family: Hack 
    style: Regular
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic
  bold_italic:
    family: Hack
    style: Bold Italic
  offset:
    x: 1
    y: 0

scrolling.history: 1000
cursor.style: Block
debug.render_timer: false
draw_bold_text_with_bright_colors: false
background_opacity: 0.75
#dynamic_title: true

colors:
  primary:
    background: '0x262A2D'
    foreground: '0xDFDFDF'
  cursor:
    text: '0x7D7D7D'
    cursor: '0xDFDFDF'
  selection:
    text: '0xEDEBD7'
    background: '0x262A3B'
  normal:
    black:   '0x32344a'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan:    '0x449dab'
    white:   '0x9699a8'
  bright:
    black:   '0x444b6a'
    red:     '0xff7a93'
    green:   '0xb9f27c'
    yellow:  '0xff9e64'
    blue:    '0x7da6ff'
    magenta: '0xbb9af7'
    cyan:    '0x0db9d7'
    white:   '0xacb0d0'

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy  }
