window:
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
  padding:
    x: 0
    y: 0

  
font:
  antialias: lcd
  hinting: true
  size: 12.0
  normal:
    family: Hack 
    style: Regular
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic
  bold_italic:
    family: Hack
    style: Bold Italic
  offset:
    x: 1
    y: 0

scrolling.history: 1000
cursor.style: Block
debug.render_timer: false
draw_bold_text_with_bright_colors: false
background_opacity: 0.75
#dynamic_title: true

colors:
  primary:
    background: '0x262A2B'
    foreground: '0xFFFFFF'
  cursor:
    text: '0x7D7D7D'
    cursor: '0xDFDFDF'
  selection:
    text: '0xEDEBD7'
    background: '0x262A3B'
  normal:
    black:   '0x181818'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xd8d8d8'
  bright:
    black:   '0x585858'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xf8f8f8'

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy  }
