env:
  TERM: xterm-256color

window:
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
  padding:
    x: 0
    y: 0

scrolling:
  history: 1000
  
font:
  antialias: lcd
  hinting: true
  size: 12.0
  normal:
    family: Hack 
    style: Regular
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic
  bold_italic:
    family: Hack
    style: Bold Italic
  offset:
    x: 1
    y: 0

debug.render_timer: false
draw_bold_text_with_bright_colors: false
background_opacity: 0.85
#dynamic_title: true

colors:
  primary:
    background: '0x262A2D'
    foreground: '0xDFDFDF'
  cursor:
    text: '0x7D7D7D'
    cursor: '0xDFDFDF'
  selection:
    text: '0xEDEBD7'
    background: '0x262A3B'
  normal:
    black:   '0x1c1f24'
    red:     '0xff6c6b'
    green:   '0x98be65'
    yellow:  '0xda8548'
    blue:    '0x51afef'
    magenta: '0xc678dd'
    cyan:    '0x5699af'
    white:   '0x202328'
  bright:
    black:   '0x5b6268'
    red:     '0xda8548'
    green:   '0x4db5bd'
    yellow:  '0xecbe7b'
    blue:    '0x3071db'
    magenta: '0xa9a1e1'
    cyan:    '0x46d9ff'
    white:   '0xdfdfdf'

cursor:
  style: Block

key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Alt,           action: IncreaseFontSize }
  - { key: Minus,    mods: Alt,           action: DecreaseFontSize }
