theme = "native"
#icons = "awesome5"

[[block]]
block = "custom"
command = "~/.script/kblayout"
interval = 0

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp3s0"
format = "{signal_strength}"
interval = 4

[[block]]
block = "time"
interval = 60
format = "%R"
