theme = "native"
icons = "awesome5"

[[block]]
block = "custom"
command = "~/.script/kblayout"
interval = 0

[[block]]
block = "sound"
step_width = 2

[[block]]
block = "net"
device = "wlp3s0"
format = "{signal_strength}"
interval = 4

[[block]]
block = "time"
format = "%R"
interval = 60
